name: Build and push image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up date-based versioning with increment
        id: version
        run: |
          CURRENT_DATE=$(date +"%Y-%m-%d")
          LATEST_TAG=$(git tag --list "${CURRENT_DATE}-v*" | sort -V | tail -n 1)
          if [ -n "$LATEST_TAG" ]; then
            CURRENT_VERSION=$(echo "$LATEST_TAG" | sed -E 's/.*-v([0-9]+)/\1/')
            NEW_VERSION=$((CURRENT_VERSION + 1))
          else
            NEW_VERSION=1
          fi
          VERSION="${CURRENT_DATE}-v${NEW_VERSION}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Set up QEMU (for multi‑arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Enable BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Build and push image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag ghcr.io/${{ github.repository }}:${{ env.VERSION }} \
            --tag ghcr.io/${{ github.repository }}:latest \
            --push \
            .

      - name: Tag the repository with the version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag ${{ env.VERSION }}
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} ${{ env.VERSION }}
